image: Visual Studio 2015

environment:
  NODEJS_VERSION: "8"
  PREBUILD_UPLOAD:
    secure: K7sMOp9tSo9MKABiOzNNaKrggNlm3RBRjI8lU0drg5hWTdmUnK7zuqH2P4fB8Q5A


platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off

branches:
  only:
    - master
    - /^v.*$/

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)
